title: LTG's URL Shortener (Powered by Jekyll)
description: The official URL shortener of LaroTayoGaming
show_downloads: false
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

repository: LaroTayoGaming/url-shortener
