title: LTG Network URL Shortener (Powered by Jekyll)
description: The official URL shortener of the LTG Network
show_downloads: false
theme: jekyll-theme-cayman

permalink: /:slug/

github:
  is_project_page: false

baseurl: ""
permalink: /:slug/
logo: /assets/logo.png

theme: jekyll-theme-minimal

plugins:
  - jekyll-redirect-from

collections:
  urls:
    output: true
    permalink: /:slug

whitelist:
  - jekyll-redirect-from

redirect_from:
  json: false

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME