title: LTG's URL Shortener (Powered by Jekyll)
description: The official URL shortener of LaroTayoGaming
show_downloads: false
theme: jekyll-theme-cayman

permalink: /:slug/

github:
  is_project_page: false

plugins:
  - jekyll-redirect-from
  - jekyll-analytics

repository: LaroTayoGaming/url-shortener
