title: LTG's URL Shortener (Powered by Jekyll)
description: The official URL shortener of LaroTayoGaming
show_downloads: false
theme: jekyll-theme-cayman

permalink: /:slug/

github:
  is_project_page: false

plugins:
  - jekyll-redirect-from
  - jekyll-analytics

repository: LaroTayoGaming/url-shortener

jekyll_analytics:
 Matomo:                   # Add, if you want to track with Matomo (former Piwik Analytics)
    url: stats.larotayogaming.com # Required - url to Matomo installation without trailing /
    siteId: "3"          # Required - replace with your Matomo site id (Write id as string)
