title: LTG Network URL Shortener (Powered by Jekyll)
description: The official URL shortener of the LTG Network
show_downloads: false
theme: jekyll-theme-cayman

permalink: /:slug/

github:
  is_project_page: false

plugins:
  - jekyll-redirect-from

repository: ltgnetwork/url-shortener