name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - ltg-gh-pages # or master before October 2020

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:  bundle update --bundler
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
